import { Audit, FindingStatus } from './types';

const STATUS_LABEL: Record<FindingStatus, string> = { open: 'Open', in_progress: 'In progress', wont_fix: "Won't fix" };
const VERDICT_LABEL: Record<Audit['verdict'], string> = {
  pass: 'Ship it',
  needs_work: 'Needs work',
  do_not_ship: 'Do not ship',
};
const RANK = { critical: 0, high: 1, medium: 2, low: 3 } as const;

/** The audit as Markdown — for pasting into a PR description, ticket or chat. */
export function auditToMarkdown(audit: Audit): string {
  const name = audit.filename && audit.filename !== 'untitled' ? audit.filename : 'Pasted code';
  const ordered = audit.findings
    .map((f, i) => ({ f, i }))
    .sort((a, b) => RANK[a.f.severity] - RANK[b.f.severity] || (a.f.line ?? Infinity) - (b.f.line ?? Infinity));
  const lines = [
    `# Code review: ${name}`,
    '',
    `**Verdict:** ${VERDICT_LABEL[audit.verdict]} · ${audit.findings.length} finding(s) · ${new Date(audit.createdAt).toLocaleString()}`,
    '',
    audit.summary,
    '',
  ];
  ordered.forEach(({ f, i }, n) => {
    const status = audit.findingStatuses?.[i];
    lines.push(
      `## F${String(n + 1).padStart(2, '0')} · ${f.severity.toUpperCase()} · ${f.title}`,
      '',
      `${f.category}${f.line != null ? ` · line ${f.line}` : ''} · ${Math.round(f.confidence * 100)}% confidence${status && status !== 'open' ? ` · ${STATUS_LABEL[status]}` : ''}`,
      '',
      f.description,
      '',
      `**Root cause:** ${f.rootCause}`,
      '',
      `**Suggested fix:** ${f.suggestedFix}`,
      '',
    );
    if (f.examplePatch) lines.push('```', f.examplePatch, '```', '');
  });
  lines.push('_Generated by Audit Bench Ai_');
  return lines.join('\n');
}
